name: anoma-envio
save_full_history: false
contracts:
  - name: ProtocolAdapter
    handler: src/EventHandlers.ts
    events:
      - event: ActionExecuted(bytes32 actionTreeRoot, uint256 actionTagCount)
      - event: ApplicationPayload(bytes32 indexed tag, uint256 index, bytes blob)
      - event: CommitmentTreeRootAdded(bytes32 root)
      - event: DiscoveryPayload(bytes32 indexed tag, uint256 index, bytes blob)
      - event: ExternalPayload(bytes32 indexed tag, uint256 index, bytes blob)
      - event: ForwarderCallExecuted(address indexed untrustedForwarder, bytes input, bytes output)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Paused(address account)
      - event: ResourcePayload(bytes32 indexed tag, uint256 index, bytes blob)
      - event: TransactionExecuted(bytes32[] tags, bytes32[] logicRefs)
      - event: Unpaused(address account)
field_selection:
  transaction_fields:
    - "hash"
    - "from"
    - "to"
    - "value"
    - "input"
# Addresses from: https://github.com/anoma/pa-evm/blob/contracts/v1.1.0/bindings/src/addresses.rs
networks:
  - id: 1 # Mainnet
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0x0eA3B55b68A3f307c8FE3fe66E443247c95F0CfF"
  - id: 42161 # Arbitrum
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0x094FCC095323080e71a037b2B1e3519c07dd84F8"
  - id: 8453 # Base
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0x094FCC095323080e71a037b2B1e3519c07dd84F8"
  - id: 10 # Optimism
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0x094FCC095323080e71a037b2B1e3519c07dd84F8"

  - id: 1313161554 # Aurora
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0xFC44b66a39fe6923Ad8d3c93bFeC369728862B68"
  - id: 56 # BNB Smart Chain
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0xFC44b66a39fe6923Ad8d3c93bFeC369728862B68"

  - id: 84532 # Base Sepolia
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0x094FCC095323080e71a037b2B1e3519c07dd84F8"
  - id: 97 # BNB Testnet
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0x33d4F0c88ef555E105Ba5e5F1aFbF34d6f650964"
  - id: 1313161555 # Aurora Testnet
    start_block: 0
    rpc_config:
      url: https://testnet.aurora.dev
    contracts:
    - name: ProtocolAdapter
      address:
        - "0x24CEc6A74A0E39eE33C8356DB8655308112f587F"

  - id: 11155111   # eth-sepolia
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
      - 0xf152bba809d6cba122579cee997a54b8f3fba417
unordered_multichain_mode: true
